# Generated by Django 5.1.6 on 2025-03-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosing_app', '0004_alter_laborderrequest_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='doctor',
        ),
        # migrations.AddField(
        #     model_name='labreport',
        #     name='doctor',
        #     field=models.ForeignKey(default='Yaw Manu', on_delete=django.db.models.deletion.CASCADE, to='diagnosing_app.doctor'),
        # ),
    ]
