# Generated by Django 5.1.6 on 2025-03-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosing_app', '0006_labreport_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/%Y/%m/%d/'),
        ),
    ]
